### PR TITLE
Remove npm depencency on Ubuntu Xenial

### PR DESCRIPTION
**Pull request by amayita**
Connects to https://github.com/artefactual-labs/ansible-atom/issues/31

### CODE REVIEW

**Comment by mamedin** [comment]
@scollazo, On Xenial `npm` command is included in `nodejs` package:

```
root@atom25-1604:~# sudo dpkg -S /usr/bin/npm
nodejs: /usr/bin/npm
``` 

But it is different in Bionic:

```
artefactual@tom25-1804:~$ sudo dpkg -S /usr/bin/npm
npm: /usr/bin/npm

artefactual@tom25-1804:~$ sudo dpkg -L nodejs | grep npm
artefactual@tom25-1804:~$ 
```

**Comment by jraddaoui** [comment]
Hi @scollazo,

Yes, we use it to install LESS in the same file at the bottom and it's also needed for Binder (`atom_drmc: "yes"`).

**Comment by jraddaoui** [comment]
Although, I think we could remove `nodejs` from Bionic.

**Comment by amayita** [comment]
> Although, I think we could remove `nodejs` from Bionic.

Thanks @jraddaoui , I'm about to test a new deploy on Bionic without `nodejs` package. I'll get back with my findings.

**Comment by amayita** [comment]
@jraddaoui `nodejs` was removed for Bionic because `npm` depends on it, so it will pull it at install.
This is ready for CR again

**Comment by amayita** [comment]
> It's better to be implicit than explicit, so instead of bringing nodejs as an npm dependecy, I would prefer to leave it listed in the role.

The thing is: it doesn't matter. `nmp` depends on `nodejs`.  If `nmp` is installed, `nodejs` will be installed too. Whether you list it or not ,it will be installed. 

The same way you don't list all the dependencies for every package you install, I see no need to list `nodejs`.  But I don't care either way. I'm just trying to clarify my motives (and @jraddaoui 's who originally requested this change).

Please let me know, @scollazo if you agree with me now :)

**Pull request merged**
