### PR TITLE
app.yml: Add some missing variables to template

### PR DESCRIPTION
**Pull request by mamedin**
The following variables have been added:

* google_analytics_institutions_dimension_index
* google_tag_manager_container_id
* csv_transform_script_name

Connects to https://github.com/artefactual-labs/ansible-atom/issues/62

### CODE REVIEW

**Comment by mamedin** [comment]
These variables were included in old atom25 template but not in role

**Review by luisilara — APPROVED** [review]
LGTM

**Review by hakamine — APPROVED** [review]

**Review by DavidHume-ArtefactualSystems — APPROVED** [review]
Looks right...

Same "atom_app_google_..." correctly replacing "app_google_..." from old external templates would mean tweaking for a couple of clients (or actually I think you've caught that in external configuration file migration playbook).

**Comment by mamedin** [comment]
> Looks right...
> 
> Same "atom_app_google_..." correctly replacing "app_google_..." from old external templates would mean tweaking for a couple of clients (or actually I think you've caught that in external configuration file migration playbook).

We can add to the group_vars file to ensure it is changed:

```
atom_app_google_...: {{ "app_google_... | default(omit) }}
```

**Pull request merged**
