### PR TITLE
Updates for 2.4.1 deployments

### PR DESCRIPTION
**Pull request by scollazo**
- Fixes the imagemagick policy.xml file to allow imagemagick to create thumbnails for pdf files
- Adds `atom_gdpr_enabled` var. When enabled, it runs the symfony script that creates the privacy page

### CODE REVIEW

**Comment by DavidHume-ArtefactualSystems** [comment]
@djjuhasz - good point on not automatically running upgrade-sql, and @scollazo I like the new flag. David, when you say "probably shouldn't put in plugins.yml" I assume you'd mean that for both the upgrade-sql code and the _add_gdpr_enabled_ flag?

Santi - as mentioned new deploys of >= 2.4.1 going forward will have the GDPR installed and not need the variable, but if the role may be used to upgrade an existing installation from 2.4.0 e.g, then (other than "probably somewhere other than plugins.yml") I confirmed a while back that add_gdpr_enabled does indeed work.

**Comment by scollazo** [comment]
Is ok if I merge this as is (with the upgrade-sql task as part of plugins.yml) , and do a refactor as part of the changes for atom 2.5?

**Comment by scollazo** [comment]
@DavidHume-ArtefactualSystems this has been rebased/upgraded for 18.04 hosts, and is ready for review again

**Comment by scollazo** [comment]
Closed in behalf of https://github.com/artefactual-labs/ansible-atom/pull/33

**Pull request closed without merging**
